import { jsPDF } from 'jspdf';

export interface CertificateData {
	event: {
		name: string;
		date?: string;
		venue?: string;
		organiserName?: string;
	};
	attendee: {
		fullName: string;
		studentId?: string;
	};
}

/**
 * Generate a PDF certificate for an event attendee
 * @param data - Certificate data including event and attendee information
 * @returns Buffer containing the PDF certificate
 */
export function generateCertificatePDF(data: CertificateData): Buffer {
	// Create a new PDF document in landscape mode (A4 size)
	const doc = new jsPDF({
		orientation: 'landscape',
		unit: 'mm',
		format: 'a4'
	});

	const pageWidth = doc.internal.pageSize.getWidth();
	const pageHeight = doc.internal.pageSize.getHeight();

	// Add decorative border
	doc.setDrawColor(41, 128, 185); // Blue color
	doc.setLineWidth(3);
	doc.rect(10, 10, pageWidth - 20, pageHeight - 20);
	doc.setLineWidth(0.5);
	doc.rect(12, 12, pageWidth - 24, pageHeight - 24);

	// Add title
	doc.setFontSize(40);
	doc.setTextColor(41, 128, 185);
	doc.text('CERTIFICATE', pageWidth / 2, 40, { align: 'center' });

	doc.setFontSize(16);
	doc.setTextColor(100, 100, 100);
	doc.text('OF ATTENDANCE', pageWidth / 2, 52, { align: 'center' });

	// Add decorative line
	doc.setDrawColor(41, 128, 185);
	doc.setLineWidth(1);
	doc.line(60, 60, pageWidth - 60, 60);

	// Add "This is to certify that"
	doc.setFontSize(14);
	doc.setTextColor(60, 60, 60);
	doc.text('This is to certify that', pageWidth / 2, 80, { align: 'center' });

	// Add attendee name
	doc.setFontSize(28);
	doc.setTextColor(0, 0, 0);
	doc.setFont('helvetica', 'bold');
	doc.text(data.attendee.fullName, pageWidth / 2, 95, { align: 'center' });

	// Add student ID if available
	if (data.attendee.studentId) {
		doc.setFontSize(12);
		doc.setTextColor(100, 100, 100);
		doc.setFont('helvetica', 'normal');
		doc.text(`Student ID: ${data.attendee.studentId}`, pageWidth / 2, 105, { align: 'center' });
	}

	// Add "has successfully attended"
	doc.setFontSize(14);
	doc.setTextColor(60, 60, 60);
	doc.text('has successfully attended', pageWidth / 2, 118, { align: 'center' });

	// Add event name
	doc.setFontSize(22);
	doc.setTextColor(41, 128, 185);
	doc.setFont('helvetica', 'bold');
	// Wrap event name if it's too long
	const maxWidth = pageWidth - 80;
	const eventNameLines = doc.splitTextToSize(data.event.name, maxWidth);
	doc.text(eventNameLines, pageWidth / 2, 133, { align: 'center' });

	// Calculate Y position for next elements based on event name lines
	const eventNameHeight = eventNameLines.length * 8;
	let currentY = 133 + eventNameHeight;

	// Add event details
	doc.setFontSize(12);
	doc.setTextColor(80, 80, 80);
	doc.setFont('helvetica', 'normal');

	if (data.event.date) {
		doc.text(`Date: ${data.event.date}`, pageWidth / 2, currentY + 5, { align: 'center' });
		currentY += 8;
	}

	if (data.event.venue) {
		doc.text(`Venue: ${data.event.venue}`, pageWidth / 2, currentY + 5, { align: 'center' });
		currentY += 8;
	}

	if (data.event.organiserName) {
		doc.text(`Organised by: ${data.event.organiserName}`, pageWidth / 2, currentY + 5, {
			align: 'center'
		});
		currentY += 8;
	}

	// Add decorative line before signature
	doc.setDrawColor(41, 128, 185);
	doc.setLineWidth(0.5);
	doc.line(60, pageHeight - 40, pageWidth - 60, pageHeight - 40);

	// Add signature line and date
	doc.setFontSize(10);
	doc.setTextColor(60, 60, 60);

	// Signature line
	doc.text('_____________________', pageWidth / 2, pageHeight - 25, { align: 'center' });
	doc.text('Authorized Signature', pageWidth / 2, pageHeight - 18, { align: 'center' });

	// Add footer
	doc.setFontSize(8);
	doc.setTextColor(150, 150, 150);
	doc.text('Generated by Student Event Management System (SEMS)', pageWidth / 2, pageHeight - 4, {
		align: 'center'
	});

	// Convert PDF to Buffer
	const pdfOutput = doc.output('arraybuffer');
	return Buffer.from(pdfOutput);
}

/**
 * Helper function to format date for certificate display
 * @param dateString - ISO date string
 * @returns Formatted date string
 */
export function formatCertificateDate(dateString: string | null | undefined): string | undefined {
	if (!dateString) return undefined;

	const date = new Date(dateString);
	return date.toLocaleDateString('en-US', {
		weekday: 'long',
		year: 'numeric',
		month: 'long',
		day: 'numeric'
	});
}
